# 【新增】顶层 display_name 用于在UI上显示，可以包含中文和空格
display_name: "通用数据采集器"

# 【新增】identity 块，用于定义插件的唯一身份
identity:
  # 【修改】将原有的 name 移到这里，并作为机器可读的ID
  name: "data_collector"
  # 【修改】将原有的 author 移到这里
  author: "aura_team" # 建议作者也使用小写、下划线的格式，便于生成 canonical_id

# 【保留】版本号
version: "1.0.0"

# 【保留】描述信息
description: "通用数据采集插件，支持HTTP、文件、RSS、数据库等多种数据源"

# 【保留】依赖关系
dependencies: { }

# 【删除】canonical_id 字段，它由框架根据 identity.author 和 identity.name 自动生成
# (例如，生成为 aura_team.data_collector)
