# -------------------
# 身份标识
# -------------------
author: "AuraCore"
name: "SystemActions"

# -------------------
# 描述性信息
# -------------------
version: "1.0.0"
description: "Aura 框架内置的核心行为（Actions），例如 tap, swipe, find_template, ocr 等。"

# -------------------
# 依赖关系
# -------------------
# 这个包中的 Action 严重依赖于核心服务包提供的服务。
# 因此，我们必须在这里声明对 'AuraCore/SystemServices' 的依赖。
# 这确保了在加载本插件之前，所有核心服务都已加载完毕。
dependencies:
  "AuraCore/SystemServices": "^1.0.0" # 要求 AuraCore/SystemServices 插件版本为 1.x.x
