# 插件在UI上显示的友好名称
display_name: "后台窗口控制器"

# 插件的唯一身份标识
identity:
  # 插件的机器可读名称
  name: "window_controller"
  # 插件的作者
  author: "aura_team"

# 插件版本
version: "1.0.0"

# 插件的详细描述
description: "一个用于Windows系统的后台窗口控制器，可以在不影响用户操作的情况下，向指定窗口发送键鼠消息。"

# 插件的依赖关系
dependencies: { }
