# 插件在UI上显示的友好名称
display_name: "State Planner"

# 插件的唯一身份标识
identity:
  # 插件的机器可读名称
  name: "state_planner"
  # 插件的作者
  author: "aura_team"

# 插件版本
version: "1.0.0"

# 插件的详细描述
description: "一个基于状态图的自动规划器，用于驱动复杂的目标导向型自动化流程。"

# 插件的依赖关系
dependencies: {}
  # 规划器可能需要调度器的能力来执行子任务
  # 这里假设调度器是核心功能，不需要显式依赖
  # 如果未来调度器也变成插件，需要在这里声明
