# -------------------
# 身份标识
# -------------------
# author: 定义了这个插件的命名空间，'AuraCore' 代表这是框架的核心部分。
author: "AuraCore"
# name: 在 'AuraCore' 命名空间下，这个插件包的名称。
name: "SystemServices"

# -------------------
# 描述性信息
# -------------------
version: "1.0.0"
description: "Aura 框架内置的核心系统服务，提供基础的视觉、OCR、设备控制和屏幕交互能力。"

# -------------------
# 依赖关系
# -------------------
# 作为最基础的服务提供者，它不依赖于任何其他插件包。
dependencies: {}
